server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://mydbinstance.cowb8w6shbou.us-east-1.rds.amazonaws.com:5432/moviedatabase
    username: upgradfsd
    password: upgradfsd

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
