server:
  servlet:
    port: 8080
    contextPath: /api

spring:

  application:
    name: movieapp-api

  datasource:
    url: jdbc:postgresql://mydbinstance.cg1lti9azghj.us-east-1.rds.amazonaws.com:5432/mydbinstance
    username: upgrad123
    password: upgrad2021fsd

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
